import type { Metadata } from 'next'
import "./globals.css"
import Provider from '@/components/providers/next_auth_Provider'
import Navigationpanel from '@/components/navigation/panel/Navigationpanel'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      
          <body className='bg-stone-950' >
            <Provider >
              <div className='w-full h-screen bg-slate-800 flex'>
                  <div>
                    <Navigationpanel/>
                  </div>
                  <div>
                     {children}
                  </div>
              </div>
              
            </Provider>
          </body>
      
    </html>
  )
}
