
import type { Metadata } from 'next'
import "./globals.css"
import Provider from '@/components/providers/next_auth_Provider'
import Navigationpanel from '@/components/navigation/panel/Navigationpanel'




export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

 
  return (
    <html lang="en" className='dark'>
      
          <body className='bg-neutral-950 h-screen overflow-hidden' >
            <Provider >
              <div className='w-full h-screen bg-neutral-950 flex'>
                  <div className=''>
                    <Navigationpanel/>
                  </div>
                  <div className='w-full max-md:w-full'>
                     {children}
                  </div>
              </div>
              
            </Provider>
    
          </body>
      
    </html>
  )
}
